/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mycompany.presentaciontutorias.Aplicacion;

/**
 *
 * @author HP
 */
public class MenuSistema extends javax.swing.JFrame {
    private Aplicacion control;
    /**
     * Creates new form MenuTutorias
     */
    public MenuSistema(Aplicacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTutorias = new javax.swing.JMenu();
        menuAlumnos = new javax.swing.JMenu();
        menuMaterias = new javax.swing.JMenu();
        menuSesiones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(54, 111, 197));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("¡Bienvenido!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 210, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 640));

        menuTutorias.setText("Administrar Tutores");
        menuTutorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTutoriasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTutorias);

        menuAlumnos.setText("Administrar Alumnos");
        jMenuBar1.add(menuAlumnos);

        menuMaterias.setText("Administrar Materias");
        jMenuBar1.add(menuMaterias);

        menuSesiones.setText("Administrar Sesiones");
        jMenuBar1.add(menuSesiones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTutoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTutoriasMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuTutores();
    }//GEN-LAST:event_menuTutoriasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuMaterias;
    private javax.swing.JMenu menuSesiones;
    private javax.swing.JMenu menuTutorias;
    // End of variables declaration//GEN-END:variables



}
