/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.ModuloTutores;

import Dominio.Tutor;
import com.mycompany.presentaciontutorias.Aplicacion;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class MenuTutores extends javax.swing.JPanel {
    private Aplicacion control;
    /**
     * Creates new form MenuTutores
     */
    public MenuTutores(Aplicacion control) {
        this.control = control;
        initComponents();
        valoresDefault();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTutores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar1 = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        txtBuscarId = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setEnabled(false);

        tablaTutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Especialidad", "E-mail", "Telefono", "Disponibilidad"
            }
        ));
        jScrollPane1.setViewportView(tablaTutores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 830, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Administrar Tutores");
        jLabel1.setEnabled(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        BtnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(204, 204, 204));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setEnabled(false);
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        BtnEliminar1.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.setEnabled(false);
        add(BtnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(204, 204, 204));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setEnabled(false);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        txtBuscarId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscarId.setEnabled(false);
        add(txtBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
        control.mostrarAgregarTutor();
    }//GEN-LAST:event_BtnAgregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTutores;
    private javax.swing.JTextField txtBuscarId;
    // End of variables declaration//GEN-END:variables


        public void CargarTabla(){
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Especialidad", "Email", "Teléfono", "Disponibilidad"}, 0
            ) {
            @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
        model.setRowCount(0);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);

        tablaTutores.setRowSorter(sorter);
        for (Tutor tutor : control.consultarTodos()) {
            Object[] fila = new Object[]{
                tutor.getId(),
                tutor.getNombre(),
                tutor.getEspecialidad(),
                tutor.getEmail(),
                tutor.getTelefono(),
                ""+tutor.getInicio() +"-" + tutor.getFin()
                };
            model.addRow(fila);
        }
        tablaTutores.setRowSelectionAllowed(true);
        tablaTutores.setColumnSelectionAllowed(false);
        tablaTutores.setCellSelectionEnabled(false);
        tablaTutores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaTutores.getTableHeader().setReorderingAllowed(false);
        tablaTutores.getTableHeader().setResizingAllowed(false);
        tablaTutores.setModel(model);
    }
    
    public void filtrarPorID() {
        String texto = txtBuscarId.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tablaTutores.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablaTutores.setRowSorter(sorter);
        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("^" + texto + "$", 0));
        }
}
    public void valoresDefault(){
        CargarTabla();
        txtBuscarId.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }
        });
    }
    

}
