/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.ModuloTutores;

import DTOs.TutorDTO;
import Dominio.Tutor;
import com.mycompany.presentaciontutorias.Aplicacion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class MenuTutores extends javax.swing.JPanel {
    private Aplicacion control;
    /**
     * Creates new form MenuTutores
     */
    public MenuTutores(Aplicacion control) {
        initComponents();
        this.control = control;
        valoresDefault();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTutores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar1 = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        txtBuscarId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setEnabled(false);

        tablaTutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaTutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTutores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 830, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Administrar Tutores");
        jLabel1.setEnabled(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        BtnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(204, 204, 204));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setEnabled(false);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        BtnEliminar1.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.setEnabled(false);
        BtnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminar1MouseClicked(evt);
            }
        });
        add(BtnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(204, 204, 204));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setEnabled(false);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        txtBuscarId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscarId.setEnabled(false);
        add(txtBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 200, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Limpiar Seleccion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
        control.mostrarAgregarTutor();
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        tablaTutores.clearSelection();
    }//GEN-LAST:event_jButton1MouseClicked

    private void tablaTutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTutoresMouseClicked
        // TODO add your handling code here:
        setTearTutor(tablaTutores.getSelectedRow());
    }//GEN-LAST:event_tablaTutoresMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
        if(tablaTutores.getSelectedRow() != -1 ){
            control.mostrarActualizarTutor();
        }else{
            JOptionPane.showMessageDialog(
                null,
                "Seleccione a un tutor antes de querer actualizarlo",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminar1MouseClicked
        // TODO add your handling code here:
        if(control.eliminarTutor(control.consultarTodos().get(tablaTutores.getSelectedRow()).getId())){
            JOptionPane.showMessageDialog(
                null,
                "El tutor fue eliminado correctamente",
                "Exito",
                JOptionPane.INFORMATION_MESSAGE
            );
            control.mostrarMenuTutores();
        }else{
            JOptionPane.showMessageDialog(
                null,
                "No se puedo eliminar al Tutor",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnEliminar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTutores;
    private javax.swing.JTextField txtBuscarId;
    // End of variables declaration//GEN-END:variables


        public void CargarTabla(){
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Especialidad", "Email", "Teléfono", "Disponibilidad"}, 0
            ) {
            @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
        model.setRowCount(0);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);

        tablaTutores.setRowSorter(sorter);
        for (Tutor tutor : control.consultarTodos()) {
            Object[] fila = new Object[]{
                tutor.getId(),
                tutor.getNombre(),
                tutor.getEspecialidad(),
                tutor.getEmail(),
                tutor.getTelefono(),
                tutor.getDisponibilidad()
                };
            model.addRow(fila);
        }
        tablaTutores.setModel(model);
        tablaTutores.setRowSelectionAllowed(true);
        tablaTutores.setColumnSelectionAllowed(false);
        tablaTutores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaTutores.getTableHeader().setReorderingAllowed(false);
        tablaTutores.getTableHeader().setResizingAllowed(false);
        
        tablaTutores.setSelectionBackground(Color.CYAN);
        tablaTutores.setSelectionForeground(Color.BLACK);
        
    }
    
    public void filtrarPorID() {
        String texto = txtBuscarId.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tablaTutores.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablaTutores.setRowSorter(sorter);
        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("^" + texto + "$", 0));
        }
}
    public void valoresDefault(){
        CargarTabla();
        txtBuscarId.getDocument().addDocumentListener(new DocumentListener() {
        @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }
        });
    }
    
    public void setTearTutor(int index){
        int filaModelo = tablaTutores.convertRowIndexToModel(index);
        DefaultTableModel model = (DefaultTableModel) tablaTutores.getModel();
        int id = (int) model.getValueAt(filaModelo, 0); 
        String nombre = (String) model.getValueAt(filaModelo, 1);
        String especialidad = (String) model.getValueAt(filaModelo, 2);
        String email = (String) model.getValueAt(filaModelo, 3);
        String telefono = (String) model.getValueAt(filaModelo, 4);
        String disponibilidad = (String) model.getValueAt(filaModelo, 5);
        
        TutorDTO tutorDTO = new TutorDTO();
        tutorDTO.setId(id);
        tutorDTO.setNombre(nombre);
        tutorDTO.setEmail(email);
        tutorDTO.setEspecialidad(especialidad);
        tutorDTO.setTelefono(telefono);
        tutorDTO.setDisponibilidad(disponibilidad);
        System.out.println("Tutor seteado a control--" + tutorDTO.toString());
        control.setTutor(tutorDTO);
    }

}
