/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.ModuloAlumnos;

import DTOs.AlumnoDTO;
import com.mycompany.presentaciontutorias.Aplicacion;
import java.awt.event.KeyEvent;

/**
 *
 * @author HP
 */
public class PanelDatosAlumno extends javax.swing.JPanel {
    private Aplicacion control;
    private AlumnoDTO alumno;
    /**
     * Creates new form PanelInformarcionAlumno
     */
    public PanelDatosAlumno(Aplicacion control) {
        this.control = control;
        initComponents();
        this.alumno = control.getAlumnoTemporal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        escuela = new javax.swing.JTextField();
        campoEdad = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        gradoEscolar = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registro Alumno");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Grado Escolar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Escuela Procedencia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Edad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, 50));

        escuela.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 300, -1));

        campoEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, -1));

        campoTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 300, -1));

        gradoEscolar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(gradoEscolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        btnContinuar.setBackground(new java.awt.Color(0, 0, 0));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarMouseClicked(evt);
            }
        });
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuAlumnos();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarMouseClicked
        // TODO add your handling code here:
        //falta logica de Armar el objeto y enviarlo a la App y de ahi a controller, 
        
        alumno.setTelefono(Integer.parseInt(campoEdad.getText()));
        alumno.setEdad(Integer.parseInt(campoTelefono.getText()));
        alumno.setEscuelaProcedencia(escuela.getText());
        alumno.setGradoEscolar(gradoEscolar.getText());
        
        control.mostrarResumenAlumno();
    }//GEN-LAST:event_btnContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField escuela;
    private javax.swing.JTextField gradoEscolar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public void valoresDefault(){
       campoEdad.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           char c = e.getKeyChar();
           if(!Character.isDigit(c)){
               e.consume();
           }
           if(campoEdad.getText().length() >= 3){
               e.consume();
           }
       }
    });
       campoTelefono.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           char c = e.getKeyChar();
           if(!Character.isDigit(c)){
               e.consume();
           }
           if(campoTelefono.getText().length() >= 10){
               e.consume();
           }
       }
    });
        gradoEscolar.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           if(gradoEscolar.getText().length() >= 50){
               e.consume();
           }
       }
    });
       escuela.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           if(escuela.getText().length() >= 50){
               e.consume();
           }
       }
    });
   }
}
