/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.ModuloAlumnos;

import DTOs.AlumnoDTO;
import com.mycompany.presentaciontutorias.Aplicacion;
import java.awt.event.KeyEvent;

/**
 *
 * @author HP
 */
public class PanelNombres extends javax.swing.JPanel {
    private Aplicacion control;
    private AlumnoDTO alumno;
    /**
     * Creates new form PanelNombres
     */
    public PanelNombres(Aplicacion control) {
        this.control = control;
        initComponents();
        this.alumno = new AlumnoDTO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoPaterno = new javax.swing.JTextField();
        campoMaterno = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        btnContinuarl = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registro Alumno");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Materno");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 90, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre(s)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Paterno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 50));

        campoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, -1));

        campoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 160, -1));

        nombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, -1));

        btnContinuarl.setBackground(new java.awt.Color(0, 0, 0));
        btnContinuarl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContinuarl.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarl.setText("Continuar");
        btnContinuarl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarlMouseClicked(evt);
            }
        });
        add(btnContinuarl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuAlumnos();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnContinuarlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarlMouseClicked
        // TODO add your handling code here:
        alumno.setNombre(nombres.getText());
        alumno.setApellidoPaterno(campoPaterno.getText());
        alumno.setApellidoMaterno(campoMaterno.getText());
        control.setAlumno(alumno);
        control.mostraDatosAlumno();
    }//GEN-LAST:event_btnContinuarlMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuarl;
    private javax.swing.JTextField campoMaterno;
    private javax.swing.JTextField campoPaterno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombres;
    // End of variables declaration//GEN-END:variables


    public void valoresDefault(){
       nombres.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           if(nombres.getText().length() >= 50){
               e.consume();
           }
       }
    });
       campoPaterno.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           if(campoPaterno.getText().length() >= 50){
               e.consume();
           }
       }
    });
       nombres.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           if(nombres.getText().length() >= 50){
               e.consume();
           }
       }
    });
   }
}
