/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.ModuloMateria;

import DTOs.MateriaDTO;
import com.mycompany.presentaciontutorias.Aplicacion;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandra
 */
public class AgregarMateria extends javax.swing.JPanel {
private Aplicacion control;

    /**
     * Creates new form AgregarMateria
     */
    public AgregarMateria(Aplicacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregarAlumo = new javax.swing.JLabel();
        lblNombreMateria = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        lblNivelEducativo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        cBoxNivelEducativo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgregarAlumo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAgregarAlumo.setText("Agregar materia");
        add(lblAgregarAlumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 16, -1, -1));

        lblNombreMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreMateria.setText("Nombre: ");
        add(lblNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 56, -1, -1));
        add(txtNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 56, 169, -1));

        lblNivelEducativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNivelEducativo.setText("Nivel educativo");
        add(lblNivelEducativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 96, -1, -1));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción:");
        add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        btnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        cBoxNivelEducativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kinder", "Primaria", "Secundaria", "Preparatoria", "Universidad" }));
        add(cBoxNivelEducativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 99, 165, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 290, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        control.mostrarMenuMaterias();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here
        crearMateria();
        Boolean confirmar = control.confirmarMateria(control.getMateria());
        if (confirmar){
            JOptionPane.showConfirmDialog(
                null,
                "materia registrada con exito",
                "Materia Registradada",
                JOptionPane.YES_OPTION
            );
            control.mostrarMenuMaterias();
        }else{
            JOptionPane.showMessageDialog(
                null,
                "Ocurrió un error al registrar la materia.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cBoxNivelEducativo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregarAlumo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNivelEducativo;
    private javax.swing.JLabel lblNombreMateria;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables

    public void crearMateria(){
        MateriaDTO materia = new MateriaDTO();
        materia.setNombre(txtNombreMateria.getText());
        materia.setNivelAcademico(cBoxNivelEducativo.getSelectedItem().toString());
        materia.setDescripcion(txtDescripcion.getText());
        control.setMateria(materia);
    }

}
