/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.ModuloMateria;

import DTOs.MateriaDTO;
import DTOs.TutorDTO;
import Dominio.Materia;
import com.mycompany.presentaciontutorias.Aplicacion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class MenuMaterias extends javax.swing.JPanel {
    private Aplicacion control;
    /**
     * Creates new form AdministrarMaterias
     */
    public MenuMaterias(Aplicacion control) {
        this.control = control;
        initComponents();
        valoresDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar1 = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        txtBuscarId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setEnabled(false);

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMaterias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 830, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Administrar Materias");
        jLabel1.setEnabled(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        BtnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(204, 204, 204));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setEnabled(false);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        BtnEliminar1.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.setEnabled(false);
        BtnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminar1MouseClicked(evt);
            }
        });
        add(BtnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(204, 204, 204));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setEnabled(false);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        txtBuscarId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscarId.setEnabled(false);
        add(txtBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 200, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Limpiar Seleccion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMateriasMouseClicked
        // TODO add your handling code here:
        setMateria(tablaMaterias.getSelectedRow());
    }//GEN-LAST:event_tablaMateriasMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
        if(tablaMaterias.getSelectedRow() != -1 ){
            control.mostrarActualizarMateria();
        }else{
            JOptionPane.showMessageDialog(
                null,
                "Seleccione una materia antes de querer actualizarla",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminar1MouseClicked
        // TODO add your handling code here:
        if(control.eliminarMateria(control.getMateria().getId())){
            JOptionPane.showMessageDialog(
                null,
                "La materia fue eliminada correctamente",
                "Exito",
                JOptionPane.INFORMATION_MESSAGE
            );
            control.mostrarMenuTutores();
        }else{
            JOptionPane.showMessageDialog(
                null,
                "No se pudo eliminar la materia",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnEliminar1MouseClicked

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
        control.mostrarAgregarMateria();
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        tablaMaterias.clearSelection();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMaterias;
    private javax.swing.JTextField txtBuscarId;
    // End of variables declaration//GEN-END:variables


        public void CargarTabla(){
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Nivel Educativo", "Descripcion"}, 0
            ) {
            @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
        model.setRowCount(0);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);

        tablaMaterias.setRowSorter(sorter);
        for (Materia materia : control.consultarMaterias()) {
            Object[] fila = new Object[]{
                materia.getId(),
                materia.getNombre(),
                materia.getNivel_Educativo(),
                materia.getDescripcion()
                };
            model.addRow(fila);
        }
        tablaMaterias.setModel(model);
        tablaMaterias.setRowSelectionAllowed(true);
        tablaMaterias.setColumnSelectionAllowed(false);
        tablaMaterias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaMaterias.getTableHeader().setReorderingAllowed(false);
        tablaMaterias.getTableHeader().setResizingAllowed(false);
        
        tablaMaterias.setSelectionBackground(Color.CYAN);
        tablaMaterias.setSelectionForeground(Color.BLACK);
        
    }
    
    public void filtrarPorID() {
        String texto = txtBuscarId.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tablaMaterias.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablaMaterias.setRowSorter(sorter);
        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("^" + texto + "$", 0));
        }
}
    public void valoresDefault(){
        CargarTabla();
        txtBuscarId.getDocument().addDocumentListener(new DocumentListener() {
        @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorID();
            }
        });
    }
    
    public void setMateria(int index){
        int filaModelo = tablaMaterias.convertRowIndexToModel(index);
        DefaultTableModel model = (DefaultTableModel) tablaMaterias.getModel();
        int id = (int) model.getValueAt(filaModelo, 0); 
        String nombre = (String) model.getValueAt(filaModelo, 1);
        String nivelEducativo = (String) model.getValueAt(filaModelo, 2);
        String descripcion = (String) model.getValueAt(filaModelo, 3);
        
        MateriaDTO materia = new MateriaDTO();
        materia.setId(id);
        materia.setNombre(nombre);
        materia.setNivelAcademico(nivelEducativo);
        materia.setDescripcion(descripcion);
  
        control.setMateria(materia);
    }
}
