/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.ModuloMateria;

import DTOs.MateriaDTO;
import com.mycompany.presentaciontutorias.Aplicacion;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ResumenMateriaActualizada extends javax.swing.JPanel {
    private Aplicacion control;
    private MateriaDTO materia;
    /**
     * Creates new form ResumenMateriaActualizada
     */
    public ResumenMateriaActualizada(Aplicacion control) {
        this.control = control;
        this.materia = control.getMateria();
        initComponents();
        llenarTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNivelEducativo = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Actualizacion de Materia");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nivel Educativo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        campoNivelEducativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoNivelEducativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 240, -1));

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 240, -1));

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        BtnConfirmar.setText("Continuar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuMaterias();
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
//        recopilarDatos();
        Boolean confirmar = control.actualizarMateria(materia);
        if (confirmar){
            JOptionPane.showMessageDialog(
                null,
                "Materia Actualizada con exito",
                "Materia Actualizada",
                JOptionPane.INFORMATION_MESSAGE
            );
        }else{
            JOptionPane.showMessageDialog(
                null,
                "Ocurrió un error al actualizar la materia.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoNivelEducativo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void llenarTextFields(){
        materia = control.getMateria();
        campoNombre.setText(materia.getNombre());
        campoDescripcion.setText(materia.getNombre());
        campoNivelEducativo.setText(materia.getNivelAcademico());
    }
}
